### ISSUE TITLE
AudioSocket is either sending or receiving but not both at the same time

### ISSUE THREAD

**Issue by pfeifel** [Microsoft/BotBuilder-RealTimeMediaCalling#27]
Is there a limitation on sending and receiving at the same time, from multiple threads? I have a solution that works if I am only receiving media, but when I start sending, it stops receiving messages.

**Comment by pfeifel** [comment]
So, found the problem in my code. thanks anyway.

**Comment by ssulzer** [comment]
@pfeifel 

Glad to hear the problem was resolved. One thing to be aware of is that if the bot performs any "blocking" operations within its AudioSocket.AudioSendStatusChanged event, that will prevent other events, such as AudioMediaReceived, from being raised. The bot's code must ensure all handlers for media platform events execute quickly and do not block. Thanks.

**Comment by pfeifel** [comment]
Hi Stephen,

Thanks for the info. It seems to be working even without waiting for the
send status to become active.

Eyal.
