### ISSUE TITLE
Video playback upside down

### ISSUE THREAD

**Issue by pfeifel** [Microsoft/BotBuilder-RealTimeMediaCalling#29]
I am sending video frames in VideoFormat.Rgb24_424x240_15Fps and they are played on the client upside down.

Any idea what could cause this?

**Comment by waboum** [comment]
Hey,

The RGB file you are trying to stream was probably generated with bottom-up DIB, meaning the frame starts with the bottom row of pixels.
Can you please generate it with top-down DIB or change the format to YUV to avoid this issue, since DIBs in YUV formats are always top-down.
For more details: https://msdn.microsoft.com/en-us/library/windows/desktop/dd407212(v=vs.85).aspx

**Comment by pfeifel** [comment]
Thanks. That was it.
